apiVersion: v1
kind: Service
metadata:
  name: sm-api-developer-portal
  namespace: sm
  labels:
    app: sm-api-developer-portal
    platform: sm-suite
spec:
  type: ClusterIP
  selector:
    app: sm-api-developer-portal
  ports:
  - name: http
    port: 8440
    targetPort: http
    protocol: TCP
