apiVersion: v1
kind: Service
metadata:
  name: sm-api-developer-portal
  namespace: sm-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8300
      targetPort: http
  selector:
    app: sm-api-developer-portal
